id: A77137818
base_file: f36D3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:51:10.114700
  last_modified_at: 2022-06-05 19:51:10.114716
