id: A77137818
base_file: f2681.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:51:10.108296
  last_modified_at: 2022-06-05 19:51:10.108318
