id: A77137818
base_file: fAA8C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:51:10.133089
  last_modified_at: 2022-06-05 19:51:10.133097
